### PR TITLE
Update pubspecs to use material package

### PR DESCRIPTION
**Pull request by xster**
https://github.com/flutter/flutter/pull/12730

### CODE REVIEW

**Comment by xster** [comment]
Understood. The code that's causing the functional change flutter/flutter#12730 is not checked in yet so I can definitely hold back if it's sensitive.

**Comment by LarkAscending** [comment]
The codelabs **fail to run** with this change on the latest alpha:
```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/eastrue/flutter
    • Framework revision e8aa40eddd (9 days ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0
```

Here is the error:
```
Running 'gradlew assembleDebug'...
Error detected in pubspec.yaml:
#/properties/flutter: unallowed additional property material_icons_font
Error building /Users/eastrue/IdeaProjects/way_way_new_friendlychat/build/app/intermediates/flutter/debug/app.flx: 1
```
Since it is a breaking change, please hold off until after Wed 11/8. Don't roll the engine change from master into alpha, and don't update the sample configuration files in flutter/friendlychat-steps until we've had a chance to test the codelabs against master.

**Comment by xster** [comment]
Yup, holding off for a while

**Pull request closed without merging**
