### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
Also, who do I talk to about actually archiving this repo?

/cc @sfshaza2

**Comment by sfshaza2** [comment]
Maybe you'd ask @Hixie? I think of him as in charge of all Flutter repos.

**Comment by Hixie** [comment]
I can archive repos. What's up?

**Comment by domesticmouse** [comment]
Hey @Hixie, can you please mark this repository [flutter/friendlychat-steps](https://github.com/flutter/friendlychat-steps) as archived? I have migrated the code from here to [flutter/codelabs](https://github.com/flutter/codelabs/tree/master/friendly_chat) as part of a push to centralize all of our codelabs in a single repo.

/cc @RedBrogdon

**Comment by Hixie** [comment]
will do

**Pull request merged**
